In [1]:
import pandas as pd

In [2]:
from chicken_dinner.pubgapi import PUBG

In [3]:
api_key = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI5NDUxNTE2MC1lNWU5LTAxMzktMjZhMi02M2UwOWQxYTU2NmEiLCJpc3MiOiJnYW1lbG9ja2VyIiwiaWF0IjoxNjI5Njg2NTA1LCJwdWIiOiJibHVlaG9sZSIsInRpdGxlIjoicHViZyIsImFwcCI6InB1YmctZXN0aW1hdG9yIn0.IxZLnOjCIKC4id8gncjWkAWM8Vpr9O_k7dJjKihuycM'

In [4]:
pubg = PUBG(api_key, 'tournament')

In [5]:
pcs = pubg.tournament('as-pcs3kr')

In [6]:
matches = pcs.get_matches()

In [7]:
for match in matches:
    tml = match.get_telemetry()
    break

## LogPlayerKill

In [8]:
from collections import deque

In [9]:
# killer 정보만 들어가므로, 다른 dataframe 과 outer join진행시 일관성을 주기위해 killer -> attacker로 바꾼다.
# victim 은 데미지를 받을때나, 죽을때나 동일하게 victim

dq = deque()
for tm in tml:
    if tm._T == 'LogPlayerKill' and tm.common.is_game >= 1.0 :
        #조건 추가로 총기사망만 챙길수 있으나 일단은 보류
#         print(tm.keys())
#         print(tm.to_dict())
        try:
            dq.append([
            tm._D, 
            tm._T, 
            tm.common.is_game, 
            tm.damage_causer_name, 
            tm.damage_reason,
            tm.damage_type_category, 
            tm.distance, 
            tm.killer.location.x,
            tm.killer.location.y,
            tm.killer.location.z,
            tm.killer.name, 
            tm.victim.location.x,
            tm.victim.location.y,
            tm.victim.location.z,
            tm.victim.name,])
        except:
            pass

In [10]:
df_lpk = pd.DataFrame(dq, 
    columns=['_D', '_T', 'is_game', 'damage_causer_name', 'damage_reason','damage_type_category',
             'distance', 'attacker_location_x', 'attacker_location_y', 'attacker_location_z', 'attacker_name',
             'victim_location_x','victim_location_y', 'victim_location_z', 'victim_name'])

In [11]:
# df_lpk

## LogPlayerAttack

In [12]:
dq = deque()
for tm in tml:
    if tm._T == 'LogPlayerAttack' and tm.common.is_game >= 1.0 :
        try:
            dq.append([
            tm._D, 
            tm._T, 
            tm.attacker.location.x,
            tm.attacker.location.y,
            tm.attacker.location.z,
            tm.attacker.name,
            tm.common.is_game, 
            tm.weapon.item_id])
        except:
            pass

In [13]:
df_lpa = pd.DataFrame(dq, 
    columns=['_D', '_T', 'attacker_location_x', 'attacker_location_y', 'attacker_location_z', 'attacker_name',
             'is_game', 'item_id'])

In [14]:
# df_lpa

## LogPlayerTakeDamage

In [15]:
dq = deque()
for tm in tml:
    if tm._T == 'LogPlayerTakeDamage' and tm.common.is_game >= 1.0:
        try:
            dq.append([
                tm._D, 
                tm._T, 
                tm.attacker.location.x, 
                tm.attacker.location.y, 
                tm.attacker.location.z,
                tm.attacker.name, 
                tm.common.is_game, 
                tm.damage, 
                tm.damage_causer_name, 
                tm.damage_reason, 
                tm.damage_type_category,
                tm.victim.location.x, 
                tm.victim.location.y, 
                tm.victim.location.z,
                tm.victim.name
            ])
        except:
            pass

In [16]:
df_lpd = pd.DataFrame(dq, 
    columns=['_D', '_T', 'attacker_location_x', 'attacker_location_y', 'attacker_location_z', 'attacker_name',
             'is_game', 'damage','damage_causer_name','damage_reason', 'damage_type_category','victim_location_x','victim_location_y', 'victim_location_z', 'victim_name'])

In [17]:
df_result = pd.concat([df_lpa, df_lpd, df_lpk])

In [18]:
df_result['damage_type_category'].unique()

array([nan, 'Damage_Instant_Fall', 'Damage_VehicleCrashHit', 'Damage_Gun',
       'Damage_Groggy', 'Damage_VehicleHit', 'Damage_Explosion_Grenade',
       'Damage_Molotov', 'Damage_BlueZone'], dtype=object)

In [19]:
df_sorted = df_result.sort_values(['_D'])

In [20]:
df_sorted['index'] = range(0, len(df_sorted))

In [21]:
# df_sorted 는 lpa , lpd, lpk  세가지를 합쳐서 시간순으로 정렬하고, index를 부여.
# 일단 damage take 정보로 교전 index를 추출

In [22]:
c1 = df_sorted['damage'].isna() == False
c2 = df_sorted['_T'] == 'LogPlayerKill'

In [23]:
df_battle = df_sorted[c1 | c2]

# 그로기 보기위해 df_2 한번 맞춤 나중에 이거 삭제

In [24]:
c1 = df_battle['damage'] == 0.0
c2 = df_battle['damage_reason'].str.contains('Shot')

In [25]:
df_groggy=df_battle[c1 & c2]
df_groggy

,_D,_T,attacker_location_x,attacker_location_y,attacker_location_z,attacker_name,is_game,item_id,damage,damage_causer_name,damage_reason,damage_type_category,victim_location_x,victim_location_y,victim_location_z,victim_name,distance,index
10,2020-09-25T09:01:24.350Z,LogPlayerTakeDamage,279779.15625,264570.031250,1673.069946,GEN_Aqua5,1.5,NaN,0.0,WeapAK47_C,LegShot,Damage_Gun,263707.03125,248102.000000,1631.000000,T1_Starlord,NaN,132
15,2020-09-25T09:01:28.591Z,LogPlayerTakeDamage,279863.81250,264670.312500,1673.789917,GEN_Aqua5,1.5,NaN,0.0,WeapAK47_C,LegShot,Damage_Gun,263496.21875,247796.171875,1646.159912,T1_Starlord,NaN,138
17,2020-09-25T09:01:29.091Z,LogPlayerTakeDamage,279863.81250,264670.312500,1673.789917,GEN_Aqua5,1.5,NaN,0.0,WeapAK47_C,ArmShot,Damage_Gun,263461.93750,247761.890625,1646.699951,T1_Starlord,NaN,141
18,2020-09-25T09:01:29.601Z,LogPlayerTakeDamage,279863.81250,264670.312500,1673.789917,GEN_Aqua5,1.5,NaN,0.0,WeapAK47_C,HeadShot,Damage_Gun,263426.43750,247738.968750,1645.849976,T1_Starlord,NaN,143
43,2020-09-25T09:03:16.355Z,LogPlayerTakeDamage,404104.18750,291798.906250,251.769989,OPGG_Alphaca,1.5,NaN,0.0,WeapHK416_C,HeadShot,Damage_Gun,403879.37500,291521.375000,211.247650,LVG_ZeniTh,NaN,226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1289,2020-09-25T09:26:47.522Z,LogPlayerTakeDamage,389880.06250,187737.812500,962.750000,DNW_LeClo,9.5,NaN,0.0,WeapBerylM762_C,TorsoShot,Damage_Gun,390209.78125,190061.109375,1057.369995,AF_Hansia,NaN,6416
1290,2020-09-25T09:26:47.771Z,LogPlayerTakeDamage,389858.59375,187741.031250,966.169983,DNW_LeClo,9.5,NaN,0.0,WeapBerylM762_C,ArmShot,Damage_Gun,390191.75000,190063.140625,1060.539917,AF_Hansia,NaN,6420
1294,2020-09-25T09:26:51.939Z,LogPlayerTakeDamage,390117.12500,188820.734375,1059.599976,DNW_LeClo,9.5,NaN,0.0,WeapBerylM762_C,TorsoShot,Damage_Gun,389911.87500,189916.562500,1197.400024,AF_Hansia,NaN,6437
1295,2020-09-25T09:26:52.024Z,LogPlayerTakeDamage,390123.50000,188830.031250,1059.660034,DNW_LeClo,9.5,NaN,0.0,WeapBerylM762_C,TorsoShot,Damage_Gun,389907.21875,189910.671875,1200.640015,AF_Hansia,NaN,6440
1296,2020-09-25T09:26:52.109Z,LogPlayerTakeDamage,390124.59375,188842.015625,1060.979980,DNW_LeClo,9.5,NaN,0.0,WeapBerylM762_C,TorsoShot,Damage_Gun,389904.71875,189907.421875,1201.929932,AF_Hansia,NaN,6442

In [26]:
dq = deque()
for tm in tml:
    if tm._T == 'LogItemEquip' and tm.common.is_game >= 1.0:
        try:
            dq.append([
                tm._D, 
                tm._T, 
                tm.character.location.x, 
                tm.character.location.y, 
                tm.character.location.z,
                tm.character.name, 
                tm.common.is_game, 
                tm.item.category,
                tm.item.item_id,
            ])
        except:
            pass

In [27]:
df_lie = pd.DataFrame(dq, 
    columns=['_D', '_T', 'character_location_x', 'character_location_y', 'character_location_z', 'character_name',
             'is_game', 'category', 'item_id'])

In [28]:
c1 = df_lie['item_id'].str.contains('Armor')
c2 = df_lie['item_id'].str.contains('Head')

In [29]:
df_groggy.columns

Index(['_D', '_T', 'attacker_location_x', 'attacker_location_y',
       'attacker_location_z', 'attacker_name', 'is_game', 'item_id', 'damage',
       'damage_causer_name', 'damage_reason', 'damage_type_category',
       'victim_location_x', 'victim_location_y', 'victim_location_z',
       'victim_name', 'distance', 'index'],
      dtype='object')

In [30]:
df_gro_part = df_groggy[['_D', '_T', 'attacker_location_x', 'attacker_location_y',
       'attacker_location_z', 'attacker_name', 'is_game', 'damage',
       'damage_causer_name', 'damage_reason', 'damage_type_category',
       'victim_location_x', 'victim_location_y', 'victim_location_z',
       'victim_name','index']]

In [31]:
df_lie_sorted = df_lie[c1 | c2].sort_values('character_name')
df_lie_sorted.columns

Index(['_D', '_T', 'character_location_x', 'character_location_y',
       'character_location_z', 'character_name', 'is_game', 'category',
       'item_id'],
      dtype='object')

In [32]:
df_lie_sorted.columns = ['_D', '_T', 'victim_location_x', 'victim_location_y',
       'victim_location_z', 'victim_name', 'is_game', 'category',
       'item_id']

In [33]:
df_gro_part2 = pd.concat([df_gro_part,df_lie_sorted])

In [34]:
df_gro_part2.sort_values('_D')

,_D,_T,attacker_location_x,attacker_location_y,attacker_location_z,attacker_name,is_game,damage,damage_causer_name,damage_reason,damage_type_category,victim_location_x,victim_location_y,victim_location_z,victim_name,index,category,item_id
0,2020-09-25T08:57:40.604Z,LogItemEquip,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,401845.34375,350876.875000,218.399994,KP_taemin,NaN,Equipment,Item_Head_E_01_Lv1_C
1,2020-09-25T08:57:40.798Z,LogItemEquip,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,361923.84375,393721.437500,3769.059814,ENT_Seongjang,NaN,Equipment,Item_Head_E_02_Lv1_C
2,2020-09-25T08:57:40.923Z,LogItemEquip,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,464841.31250,649522.562500,150.160004,emT_Hwarang,NaN,Equipment,Item_Armor_E_01_Lv1_C
5,2020-09-25T08:57:42.104Z,LogItemEquip,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,362172.62500,393520.562500,3769.059814,ENT_Seongjang,NaN,Equipment,Item_Armor_E_01_Lv1_C
6,2020-09-25T08:57:42.327Z,LogItemEquip,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,383224.90625,473778.906250,2325.159912,OPGG_Silky,NaN,Equipment,Item_Armor_D_01_Lv2_C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1289,2020-09-25T09:26:47.522Z,LogPlayerTakeDamage,389880.06250,187737.812500,962.750000,DNW_LeClo,9.5,0.0,WeapBerylM762_C,TorsoShot,Damage_Gun,390209.78125,190061.109375,1057.369995,AF_Hansia,6416.0,NaN,NaN
1290,2020-09-25T09:26:47.771Z,LogPlayerTakeDamage,389858.59375,187741.031250,966.169983,DNW_LeClo,9.5,0.0,WeapBerylM762_C,ArmShot,Damage_Gun,390191.75000,190063.140625,1060.539917,AF_Hansia,6420.0,NaN,NaN
1294,2020-09-25T09:26:51.939Z,LogPlayerTakeDamage,390117.12500,188820.734375,1059.599976,DNW_LeClo,9.5,0.0,WeapBerylM762_C,TorsoShot,Damage_Gun,389911.87500,189916.562500,1197.400024,AF_Hansia,6437.0,NaN,NaN
1295,2020-09-25T09:26:52.024Z,LogPlayerTakeDamage,390123.50000,188830.031250,1059.660034,DNW_LeClo,9.5,0.0,WeapBerylM762_C,TorsoShot,Damage_Gun,389907.21875,189910.671875,1200.640015,AF_Hansia,6440.0,NaN,NaN
1296,2020-09-25T09:26:52.109Z,LogPlayerTakeDamage,390124.59375,188842.015625,1060.979980,DNW_LeClo,9.5,0.0,WeapBerylM762_C,TorsoShot,Damage_Gun,389904.71875,189907.421875,1201.929932,AF_Hansia,6442.0,NaN,NaN

In [35]:
df_lpd_sum = df_lpd.groupby('damage_causer_name')[['damage']].sum()

In [36]:
df_lpd_cnt = df_lpd.groupby('damage_causer_name')[['damage']].count()

In [37]:
df_lpd_part = df_lpd_sum.copy()

In [38]:
df_lpd_part['count'] = df_lpd_cnt

In [39]:
df_lpd_part

                                damage  count
damage_causer_name
BP_FireEffectController_C    16.000000      4
BP_MolotovFireDebuff_C       50.000000      5
BP_Motorbike_04_C            10.531859      1
Dacia_A_01_v2_C               9.999435      3
Dacia_A_03_v2_Esports_C      25.868864      2
PlayerFemale_A_C            104.932492    721
PlayerMale_A_C                9.919998     59
ProjGrenade_C               657.296488     23
Uaz_B_01_C                   25.023775      2
Uaz_B_01_esports_C          121.436272      4
WeapAK47_C                  578.264177     47
WeapBerylM762_C            2331.334953    138
WeapBizonPP19_C             153.995041     10
WeapFNFal_C                6131.730491    225
WeapGroza_C                  53.917297      2
WeapHK416_C                 225.142809     11
WeapMini14_C                756.651451     35
WeapSKS_C                   217.668428     17

In [40]:
list(df_lpd['damage_causer_name'].unique())

['PlayerFemale_A_C',
 'Uaz_B_01_esports_C',
 'WeapAK47_C',
 'WeapHK416_C',
 'PlayerMale_A_C',
 'BP_Motorbike_04_C',
 'WeapFNFal_C',
 'WeapMini14_C',
 'Dacia_A_03_v2_Esports_C',
 'WeapSKS_C',
 'WeapBerylM762_C',
 'ProjGrenade_C',
 'BP_FireEffectController_C',
 'BP_MolotovFireDebuff_C',
 'Uaz_B_01_C',
 'WeapBizonPP19_C',
 'WeapGroza_C',
 'Dacia_A_01_v2_C']

In [41]:
dcm_list = ['WeapBerylM762_C',
 'WeapFNFal_C',
 'WeapSKS_C',
 'WeapMini14_C',
 'WeapHK416_C',
 'WeapAK47_C',
 'WeapSCAR-L_C']

In [42]:
for dcm in dcm_list:
    print(dcm)
    print(df_lpd[df_lpd['damage_causer_name'] == dcm]['damage'].describe())
    print()

WeapBerylM762_C
count    138.000000
mean      16.893732
std       16.630524
min        0.000000
25%        0.000000
50%       20.110476
75%       27.267547
max       87.000000
Name: damage, dtype: float64

WeapFNFal_C
count    225.000000
mean      27.252136
std       19.968255
min        0.000000
25%       15.295591
50%       28.402166
75%       35.910000
max      100.000000
Name: damage, dtype: float64

WeapSKS_C
count    17.000000
mean     12.804025
std      14.506890
min       0.000000
25%       0.000000
50%       0.000000
75%      28.724567
max      31.916414
Name: damage, dtype: float64

WeapMini14_C
count    35.000000
mean     21.618613
std      12.624360
min       0.000000
25%      15.778495
50%      24.866545
75%      27.697730
max      55.757420
Name: damage, dtype: float64

WeapHK416_C
count    11.000000
mean     20.467528
std      24.673260
min       0.000000
25%       0.000000
50%       5.173489
75%      42.572520
max      56.058113
Name: damage, dtype: float64

WeapAK47_C
count    47.000000
mean     12.303493
std      16.338736
min       0.000000
25%       0.000000
50%       0.000000
75%      26.085000
max      66.155380
Name: damage, dtype: float64

WeapSCAR-L_C
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: damage, dtype: float64

In [43]:
df_lpd.describe()

,attacker_location_x,attacker_location_y,attacker_location_z,is_game,damage,victim_location_x,victim_location_y,victim_location_z
count,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000
mean,368770.355197,199328.810172,3958.711239,5.139037,8.769835,367948.707374,199633.108528,4070.079975
std,31206.769921,34550.480096,2832.569823,1.693596,16.342181,31997.793050,33584.076634,2784.856145
min,175247.156250,131833.390625,41.840000,1.000000,0.000000,177404.953125,131786.062500,94.459999
25%,350168.218750,183300.000000,1918.859985,4.500000,0.000000,349567.312500,184122.671875,1974.719971
50%,372941.031250,193274.171875,2698.119873,5.000000,0.000000,370586.343750,193461.140625,3030.919922
75%,385089.750000,209869.000000,5706.330078,6.000000,16.469316,384129.312500,209418.812500,5699.109863
max,670494.562500,689877.250000,19198.355469,9.500000,100.000000,670494.562500,689877.250000,19198.355469

In [44]:
# 교전완성은 이번주.

# 그로기값보정도 이번주

# 오늘,목요일을 그렇게 진행하고

# 금요일은 최종프로젝트 준비.

# 교전에 대한 정의도 추가하는게 바람직함.

In [45]:
# c1 = df_lie['item_id'].str.contains('Armor')
# c2 = df_lie['item_id'].str.contains('Head')

In [ ]:
df_battle

In [57]:
df_dmg = df_gro_part2[['_D', '_T','damage', 'damage_causer_name','damage_reason','victim_name', 'category', 'item_id','index']]
df_dmg.sort_values('_D', inplace=True)
df_dmg

<ipython-input-57-b38150f6c5eb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dmg.sort_values('_D', inplace=True)

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,category,item_id,index
0,2020-09-25T08:57:40.604Z,LogItemEquip,NaN,NaN,NaN,KP_taemin,Equipment,Item_Head_E_01_Lv1_C,NaN
1,2020-09-25T08:57:40.798Z,LogItemEquip,NaN,NaN,NaN,ENT_Seongjang,Equipment,Item_Head_E_02_Lv1_C,NaN
2,2020-09-25T08:57:40.923Z,LogItemEquip,NaN,NaN,NaN,emT_Hwarang,Equipment,Item_Armor_E_01_Lv1_C,NaN
5,2020-09-25T08:57:42.104Z,LogItemEquip,NaN,NaN,NaN,ENT_Seongjang,Equipment,Item_Armor_E_01_Lv1_C,NaN
6,2020-09-25T08:57:42.327Z,LogItemEquip,NaN,NaN,NaN,OPGG_Silky,Equipment,Item_Armor_D_01_Lv2_C,NaN
...,...,...,...,...,...,...,...,...,...
1289,2020-09-25T09:26:47.522Z,LogPlayerTakeDamage,0.0,WeapBerylM762_C,TorsoShot,AF_Hansia,NaN,NaN,6416.0
1290,2020-09-25T09:26:47.771Z,LogPlayerTakeDamage,0.0,WeapBerylM762_C,ArmShot,AF_Hansia,NaN,NaN,6420.0
1294,2020-09-25T09:26:51.939Z,LogPlayerTakeDamage,0.0,WeapBerylM762_C,TorsoShot,AF_Hansia,NaN,NaN,6437.0
1295,2020-09-25T09:26:52.024Z,LogPlayerTakeDamage,0.0,WeapBerylM762_C,TorsoShot,AF_Hansia,NaN,NaN,6440.0
1296,2020-09-25T09:26:52.109Z,LogPlayerTakeDamage,0.0,WeapBerylM762_C,TorsoShot,AF_Hansia,NaN,NaN,6442.0

In [58]:
c1 = df_dmg['item_id'].str.contains('Armor')
c2 = df_dmg['item_id'].str.contains('Head')

In [59]:
df_dmg['index']= range(0,len(df_dmg))

<ipython-input-59-6259500ba5c1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dmg['index']= range(0,len(df_dmg))

In [60]:
df_temp = pd.DataFrame(columns=list(df_dmg.columns))
for victim in list(df_dmg['victim_name'].unique()):
    c3 = df_dmg['victim_name']==victim
    try:
        df_dmg[c1 &c3].tail(1)['index']
    except:
        pass
    else:
        df_temp = df_temp.append(df_dmg[c1 &c3].tail(1))
        
    try:
        df_dmg[c2 &c3].tail(1)['index']
    except:
        pass
    else:
        df_temp = df_temp.append(df_dmg[c2 &c3].tail(1))

In [61]:
df_temp2 = df_temp.sort_values('_D')
df_temp3 = df_temp2[['victim_name', 'item_id']].sort_values('victim_name')
df_temp3['item_lvl'] = df_temp3['item_id'].str[-3]
df_temp3['item_type'] = df_temp3['item_id'].str.split('_').str[1]
df_temp4 = df_temp3[['victim_name', 'item_lvl', 'item_type']]
df_temp4

     victim_name item_lvl item_type
767        AF_EJ        2     Armor
561        AF_EJ        2      Head
562    AF_Hansia        2      Head
676    AF_Hansia        3     Armor
533     AF_R0wha        2      Head
..           ...      ...       ...
733  emT_Hwarang        3     Armor
159  emT_Hwarang        2      Head
77      emT_Piky        2     Armor
576     emT_Piky        2      Head
161  emT_YunJong        3     Armor

[125 rows x 3 columns]

### Groggy  상태의 Damage 보정작업.

In [165]:
df_partial = df_battle[df_battle['damage_type_category'] == 'Damage_Gun'][['_D', '_T', 'damage','damage_causer_name','damage_reason','victim_name','index']]
df_partial

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index
3,2020-09-25T09:01:10.186Z,LogPlayerTakeDamage,31.020000,WeapAK47_C,TorsoShot,T1_Starlord,41
4,2020-09-25T09:01:11.376Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,T1_Starlord,55
5,2020-09-25T09:01:16.826Z,LogPlayerTakeDamage,23.295559,WeapHK416_C,TorsoShot,T1_Starlord,90
6,2020-09-25T09:01:20.887Z,LogPlayerTakeDamage,17.484440,WeapAK47_C,HeadShot,T1_Starlord,120
10,2020-09-25T09:01:24.350Z,LogPlayerTakeDamage,0.000000,WeapAK47_C,LegShot,T1_Starlord,132
...,...,...,...,...,...,...,...
1304,2020-09-25T09:26:54.721Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,DNW_Draft,6475
1305,2020-09-25T09:26:54.900Z,LogPlayerTakeDamage,27.600000,WeapBerylM762_C,TorsoShot,AF_R0wha,6482
1306,2020-09-25T09:26:54.936Z,LogPlayerTakeDamage,27.600000,WeapBerylM762_C,TorsoShot,AF_R0wha,6485
1307,2020-09-25T09:26:55.025Z,LogPlayerTakeDamage,17.200003,WeapBerylM762_C,LegShot,AF_R0wha,6490
59,2020-09-25T09:26:55.036Z,LogPlayerKill,NaN,WeapBerylM762_C,LegShot,AF_R0wha,6493

In [166]:
df_partial.columns

Index(['_D', '_T', 'damage', 'damage_causer_name', 'damage_reason',
       'victim_name', 'index'],
      dtype='object')

In [167]:
df_partial = pd.merge(df_partial, df_temp4[df_temp4['item_type'] == 'Head'][['victim_name','item_lvl']], how='outer', on='victim_name')
df_partial.columns = ['_D', '_T', 'damage', 'damage_causer_name', 'damage_reason',
       'victim_name', 'index', 'head']
df_partial

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index,head
0,2020-09-25T09:01:10.186Z,LogPlayerTakeDamage,31.020000,WeapAK47_C,TorsoShot,T1_Starlord,41,2
1,2020-09-25T09:01:11.376Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,T1_Starlord,55,2
2,2020-09-25T09:01:16.826Z,LogPlayerTakeDamage,23.295559,WeapHK416_C,TorsoShot,T1_Starlord,90,2
3,2020-09-25T09:01:20.887Z,LogPlayerTakeDamage,17.484440,WeapAK47_C,HeadShot,T1_Starlord,120,2
4,2020-09-25T09:01:24.350Z,LogPlayerTakeDamage,0.000000,WeapAK47_C,LegShot,T1_Starlord,132,2
...,...,...,...,...,...,...,...,...
519,2020-09-25T09:19:52.731Z,LogPlayerTakeDamage,0.000000,WeapBerylM762_C,TorsoShot,AZG_SexyChan,5453,2
520,2020-09-25T09:19:52.732Z,LogPlayerKill,NaN,WeapBerylM762_C,TorsoShot,AZG_SexyChan,5454,2
521,2020-09-25T09:26:54.531Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,DNW_Draft,6467,2
522,2020-09-25T09:26:54.617Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,DNW_Draft,6471,2
523,2020-09-25T09:26:54.721Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,DNW_Draft,6475,2

In [168]:
df_partial = pd.merge(df_partial, df_temp4[df_temp4['item_type'] == 'Armor'][['victim_name','item_lvl']], how='outer', on='victim_name')
df_partial.columns = ['_D', '_T', 'damage', 'damage_causer_name', 'damage_reason',
       'victim_name','index', 'head', 'armor']
df_partial

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index,head,armor
0,2020-09-25T09:01:10.186Z,LogPlayerTakeDamage,31.020000,WeapAK47_C,TorsoShot,T1_Starlord,41,2,2
1,2020-09-25T09:01:11.376Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,T1_Starlord,55,2,2
2,2020-09-25T09:01:16.826Z,LogPlayerTakeDamage,23.295559,WeapHK416_C,TorsoShot,T1_Starlord,90,2,2
3,2020-09-25T09:01:20.887Z,LogPlayerTakeDamage,17.484440,WeapAK47_C,HeadShot,T1_Starlord,120,2,2
4,2020-09-25T09:01:24.350Z,LogPlayerTakeDamage,0.000000,WeapAK47_C,LegShot,T1_Starlord,132,2,2
...,...,...,...,...,...,...,...,...,...
519,2020-09-25T09:19:52.731Z,LogPlayerTakeDamage,0.000000,WeapBerylM762_C,TorsoShot,AZG_SexyChan,5453,2,2
520,2020-09-25T09:19:52.732Z,LogPlayerKill,NaN,WeapBerylM762_C,TorsoShot,AZG_SexyChan,5454,2,2
521,2020-09-25T09:26:54.531Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,DNW_Draft,6467,2,2
522,2020-09-25T09:26:54.617Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,DNW_Draft,6471,2,2
523,2020-09-25T09:26:54.721Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,DNW_Draft,6475,2,2

In [169]:
df_partial.dropna(inplace=True)

In [170]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [171]:
le = LabelEncoder()
dcn = le.fit_transform(df_partial['damage_causer_name'])
# dcn

In [172]:
df_partial['label_dcn'] = dcn
df_partial

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index,head,armor,label_dcn
0,2020-09-25T09:01:10.186Z,LogPlayerTakeDamage,31.020000,WeapAK47_C,TorsoShot,T1_Starlord,41,2,2,0
1,2020-09-25T09:01:11.376Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,T1_Starlord,55,2,2,0
2,2020-09-25T09:01:16.826Z,LogPlayerTakeDamage,23.295559,WeapHK416_C,TorsoShot,T1_Starlord,90,2,2,5
3,2020-09-25T09:01:20.887Z,LogPlayerTakeDamage,17.484440,WeapAK47_C,HeadShot,T1_Starlord,120,2,2,0
4,2020-09-25T09:01:24.350Z,LogPlayerTakeDamage,0.000000,WeapAK47_C,LegShot,T1_Starlord,132,2,2,0
...,...,...,...,...,...,...,...,...,...,...
518,2020-09-25T09:19:52.578Z,LogPlayerTakeDamage,0.000000,WeapBerylM762_C,HeadShot,AZG_SexyChan,5447,2,2,1
519,2020-09-25T09:19:52.731Z,LogPlayerTakeDamage,0.000000,WeapBerylM762_C,TorsoShot,AZG_SexyChan,5453,2,2,1
521,2020-09-25T09:26:54.531Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,DNW_Draft,6467,2,2,0
522,2020-09-25T09:26:54.617Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,DNW_Draft,6471,2,2,0
523,2020-09-25T09:26:54.721Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,DNW_Draft,6475,2,2,0

In [173]:
dr = le.fit_transform(df_partial['damage_reason'])
# dr

In [174]:
df_partial['label_dr'] = dr
df_partial

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index,head,armor,label_dcn,label_dr
0,2020-09-25T09:01:10.186Z,LogPlayerTakeDamage,31.020000,WeapAK47_C,TorsoShot,T1_Starlord,41,2,2,0,4
1,2020-09-25T09:01:11.376Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,T1_Starlord,55,2,2,0,4
2,2020-09-25T09:01:16.826Z,LogPlayerTakeDamage,23.295559,WeapHK416_C,TorsoShot,T1_Starlord,90,2,2,5,4
3,2020-09-25T09:01:20.887Z,LogPlayerTakeDamage,17.484440,WeapAK47_C,HeadShot,T1_Starlord,120,2,2,0,1
4,2020-09-25T09:01:24.350Z,LogPlayerTakeDamage,0.000000,WeapAK47_C,LegShot,T1_Starlord,132,2,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...
518,2020-09-25T09:19:52.578Z,LogPlayerTakeDamage,0.000000,WeapBerylM762_C,HeadShot,AZG_SexyChan,5447,2,2,1,1
519,2020-09-25T09:19:52.731Z,LogPlayerTakeDamage,0.000000,WeapBerylM762_C,TorsoShot,AZG_SexyChan,5453,2,2,1,4
521,2020-09-25T09:26:54.531Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,DNW_Draft,6467,2,2,0,4
522,2020-09-25T09:26:54.617Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,DNW_Draft,6471,2,2,0,4
523,2020-09-25T09:26:54.721Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,DNW_Draft,6475,2,2,0,4

In [175]:
df_partial2 = df_partial[['damage', 'label_dcn', 'label_dr', 'head', 'armor']]
df_partial2

        damage  label_dcn  label_dr head armor
0    31.020000          0         4    2     2
1    28.199999          0         4    2     2
2    23.295559          5         4    2     2
3    17.484440          0         1    2     2
4     0.000000          0         2    2     2
..         ...        ...       ...  ...   ...
518   0.000000          1         1    2     2
519   0.000000          1         4    2     2
521  26.789999          0         4    2     2
522  26.789999          0         4    2     2
523  28.199999          0         4    2     2

[469 rows x 5 columns]

In [176]:
df_train = df_partial2[df_partial['damage'] != 0]
df_test = df_partial2[df_partial['damage'] == 0]

In [177]:
df_train

        damage  label_dcn  label_dr head armor
0    31.020000          0         4    2     2
1    28.199999          0         4    2     2
2    23.295559          5         4    2     2
3    17.484440          0         1    2     2
15   12.704788          6         0    2     2
..         ...        ...       ...  ...   ...
514  27.600000          1         4    2     2
515  20.859999          1         4    2     2
521  26.789999          0         4    2     2
522  26.789999          0         4    2     2
523  28.199999          0         4    2     2

[332 rows x 5 columns]

In [178]:
X = df_train.drop('damage', axis=1)
X

     label_dcn  label_dr head armor
0            0         4    2     2
1            0         4    2     2
2            5         4    2     2
3            0         1    2     2
15           6         0    2     2
..         ...       ...  ...   ...
514          1         4    2     2
515          1         4    2     2
521          0         4    2     2
522          0         4    2     2
523          0         4    2     2

[332 rows x 4 columns]

In [179]:
y = df_train[['damage']]
y

        damage
0    31.020000
1    28.199999
2    23.295559
3    17.484440
15   12.704788
..         ...
514  27.600000
515  20.859999
521  26.789999
522  26.789999
523  28.199999

[332 rows x 1 columns]

In [180]:
line_fitter = LinearRegression()
line_fitter.fit(X, y)

LinearRegression()

In [181]:
df_test[['label_dcn', 'label_dr', 'head', 'armor']]

     label_dcn  label_dr head armor
4            0         2    2     2
5            0         2    2     2
6            0         0    2     2
7            0         1    2     2
22           1         2    2     2
..         ...       ...  ...   ...
504          1         1    2     3
516          1         3    2     2
517          1         4    2     2
518          1         1    2     2
519          1         4    2     2

[137 rows x 4 columns]

In [182]:
dmg_predict = line_fitter.predict(df_test[['label_dcn', 'label_dr', 'head', 'armor']])
# dmg_predict

In [183]:
df_test['predict'] = dmg_predict

<ipython-input-183-f95bfd876181>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['predict'] = dmg_predict

In [184]:
df_test

     damage  label_dcn  label_dr head armor    predict
4       0.0          0         2    2     2  30.776492
5       0.0          0         2    2     2  30.776492
6       0.0          0         0    2     2  34.151149
7       0.0          0         1    2     2  32.463821
22      0.0          1         2    2     2  31.258232
..      ...        ...       ...  ...   ...        ...
504     0.0          1         1    2     3  30.785752
516     0.0          1         3    2     2  29.570903
517     0.0          1         4    2     2  27.883575
518     0.0          1         1    2     2  32.945560
519     0.0          1         4    2     2  27.883575

[137 rows x 6 columns]

In [185]:
df_partial_copy = df_partial.copy()

In [186]:
df_partial.loc[df_partial['damage'] == 0, 'damage' ] = df_test['predict']

In [187]:
df_partial

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index,head,armor,label_dcn,label_dr
0,2020-09-25T09:01:10.186Z,LogPlayerTakeDamage,31.020000,WeapAK47_C,TorsoShot,T1_Starlord,41,2,2,0,4
1,2020-09-25T09:01:11.376Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,T1_Starlord,55,2,2,0,4
2,2020-09-25T09:01:16.826Z,LogPlayerTakeDamage,23.295559,WeapHK416_C,TorsoShot,T1_Starlord,90,2,2,5,4
3,2020-09-25T09:01:20.887Z,LogPlayerTakeDamage,17.484440,WeapAK47_C,HeadShot,T1_Starlord,120,2,2,0,1
4,2020-09-25T09:01:24.350Z,LogPlayerTakeDamage,30.776492,WeapAK47_C,LegShot,T1_Starlord,132,2,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...
518,2020-09-25T09:19:52.578Z,LogPlayerTakeDamage,32.945560,WeapBerylM762_C,HeadShot,AZG_SexyChan,5447,2,2,1,1
519,2020-09-25T09:19:52.731Z,LogPlayerTakeDamage,27.883575,WeapBerylM762_C,TorsoShot,AZG_SexyChan,5453,2,2,1,4
521,2020-09-25T09:26:54.531Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,DNW_Draft,6467,2,2,0,4
522,2020-09-25T09:26:54.617Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,DNW_Draft,6471,2,2,0,4
523,2020-09-25T09:26:54.721Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,DNW_Draft,6475,2,2,0,4

In [188]:
df_partial_copy

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index,head,armor,label_dcn,label_dr
0,2020-09-25T09:01:10.186Z,LogPlayerTakeDamage,31.020000,WeapAK47_C,TorsoShot,T1_Starlord,41,2,2,0,4
1,2020-09-25T09:01:11.376Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,T1_Starlord,55,2,2,0,4
2,2020-09-25T09:01:16.826Z,LogPlayerTakeDamage,23.295559,WeapHK416_C,TorsoShot,T1_Starlord,90,2,2,5,4
3,2020-09-25T09:01:20.887Z,LogPlayerTakeDamage,17.484440,WeapAK47_C,HeadShot,T1_Starlord,120,2,2,0,1
4,2020-09-25T09:01:24.350Z,LogPlayerTakeDamage,0.000000,WeapAK47_C,LegShot,T1_Starlord,132,2,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...
518,2020-09-25T09:19:52.578Z,LogPlayerTakeDamage,0.000000,WeapBerylM762_C,HeadShot,AZG_SexyChan,5447,2,2,1,1
519,2020-09-25T09:19:52.731Z,LogPlayerTakeDamage,0.000000,WeapBerylM762_C,TorsoShot,AZG_SexyChan,5453,2,2,1,4
521,2020-09-25T09:26:54.531Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,DNW_Draft,6467,2,2,0,4
522,2020-09-25T09:26:54.617Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,DNW_Draft,6471,2,2,0,4
523,2020-09-25T09:26:54.721Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,DNW_Draft,6475,2,2,0,4