In [1]:
import pandas as pd

In [2]:
from chicken_dinner.pubgapi import PUBG

In [3]:
api_key = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI5NDUxNTE2MC1lNWU5LTAxMzktMjZhMi02M2UwOWQxYTU2NmEiLCJpc3MiOiJnYW1lbG9ja2VyIiwiaWF0IjoxNjI5Njg2NTA1LCJwdWIiOiJibHVlaG9sZSIsInRpdGxlIjoicHViZyIsImFwcCI6InB1YmctZXN0aW1hdG9yIn0.IxZLnOjCIKC4id8gncjWkAWM8Vpr9O_k7dJjKihuycM'

In [4]:
pubg = PUBG(api_key, 'tournament')

In [5]:
pcs = pubg.tournament('as-pcs3kr')

In [6]:
matches = pcs.get_matches()

In [7]:
for match in matches:
    tml = match.get_telemetry()
    break

## LogPlayerKill

In [8]:
from collections import deque

In [9]:
# killer 정보만 들어가므로, 다른 dataframe 과 outer join진행시 일관성을 주기위해 killer -> attacker로 바꾼다.
# victim 은 데미지를 받을때나, 죽을때나 동일하게 victim

dq = deque()
for tm in tml:
    if tm._T == 'LogPlayerKill' and tm.common.is_game >= 1.0 :
        #조건 추가로 총기사망만 챙길수 있으나 일단은 보류
#         print(tm.keys())
#         print(tm.to_dict())
        try:
            dq.append([
            tm._D, 
            tm._T, 
            tm.common.is_game, 
            tm.damage_causer_name, 
            tm.damage_reason,
            tm.damage_type_category, 
            tm.distance, 
            tm.killer.location.x,
            tm.killer.location.y,
            tm.killer.location.z,
            tm.killer.name, 
            tm.victim.location.x,
            tm.victim.location.y,
            tm.victim.location.z,
            tm.victim.name,])
        except:
            pass

In [10]:
df_lpk = pd.DataFrame(dq, 
    columns=['_D', '_T', 'is_game', 'damage_causer_name', 'damage_reason','damage_type_category',
             'distance', 'attacker_location_x', 'attacker_location_y', 'attacker_location_z', 'attacker_name',
             'victim_location_x','victim_location_y', 'victim_location_z', 'victim_name'])

In [11]:
# df_lpk

## LogPlayerAttack

In [12]:
dq = deque()
for tm in tml:
    if tm._T == 'LogPlayerAttack' and tm.common.is_game >= 1.0 :
        try:
            dq.append([
            tm._D, 
            tm._T, 
            tm.attacker.location.x,
            tm.attacker.location.y,
            tm.attacker.location.z,
            tm.attacker.name,
            tm.common.is_game, 
            tm.weapon.item_id])
        except:
            pass

In [13]:
df_lpa = pd.DataFrame(dq, 
    columns=['_D', '_T', 'attacker_location_x', 'attacker_location_y', 'attacker_location_z', 'attacker_name',
             'is_game', 'item_id'])

In [14]:
# df_lpa

## LogPlayerTakeDamage

In [15]:
dq = deque()
for tm in tml:
    if tm._T == 'LogPlayerTakeDamage' and tm.common.is_game >= 1.0:
        try:
            dq.append([
                tm._D, 
                tm._T, 
                tm.attacker.location.x, 
                tm.attacker.location.y, 
                tm.attacker.location.z,
                tm.attacker.name, 
                tm.common.is_game, 
                tm.damage, 
                tm.damage_causer_name, 
                tm.damage_reason, 
                tm.damage_type_category,
                tm.victim.location.x, 
                tm.victim.location.y, 
                tm.victim.location.z,
                tm.victim.name
            ])
        except:
            pass

In [16]:
df_lpd = pd.DataFrame(dq, 
    columns=['_D', '_T', 'attacker_location_x', 'attacker_location_y', 'attacker_location_z', 'attacker_name',
             'is_game', 'damage','damage_causer_name','damage_reason', 'damage_type_category','victim_location_x','victim_location_y', 'victim_location_z', 'victim_name'])

In [17]:
df_result = pd.concat([df_lpa, df_lpd, df_lpk])

In [18]:
df_result['damage_type_category'].unique()

array([nan, 'Damage_VehicleCrashHit', 'Damage_Instant_Fall',
       'Damage_VehicleHit', 'Damage_Gun', 'Damage_Groggy',
       'Damage_Explosion_Grenade', 'Damage_Molotov'], dtype=object)

In [19]:
df_sorted = df_result.sort_values(['_D'])

In [20]:
df_sorted['index'] = range(0, len(df_sorted))

In [21]:
# df_sorted 는 lpa , lpd, lpk  세가지를 합쳐서 시간순으로 정렬하고, index를 부여.
# 일단 damage take 정보로 교전 index를 추출

In [22]:
c1 = df_sorted['damage'].isna() == False
c2 = df_sorted['_T'] == 'LogPlayerKill'

In [23]:
df_battle = df_sorted[c1 | c2]

# 그로기 보기위해 df_2 한번 맞춤 나중에 이거 삭제

In [24]:
c1 = df_battle['damage'] == 0.0
c2 = df_battle['damage_reason'].str.contains('Shot')

In [25]:
df_groggy=df_battle[c1 & c2]
df_groggy

,_D,_T,attacker_location_x,attacker_location_y,attacker_location_z,attacker_name,is_game,item_id,damage,damage_causer_name,damage_reason,damage_type_category,victim_location_x,victim_location_y,victim_location_z,victim_name,distance,index
19,2020-10-10T12:14:37.173Z,LogPlayerTakeDamage,345907.90625,385171.50000,4348.770020,GEN_Pio,1.5,NaN,0.0,WeapFNFal_C,TorsoShot,Damage_Gun,350164.68750,385090.28125,3858.129883,T1_Rex,NaN,395
23,2020-10-10T12:14:39.547Z,LogPlayerTakeDamage,333806.43750,341769.06250,2036.659912,GEN_Loki,1.5,NaN,0.0,WeapMini14_C,LegShot,Damage_Gun,350104.59375,385271.62500,3874.539795,T1_Rex,NaN,403
25,2020-10-10T12:14:40.486Z,LogPlayerTakeDamage,333806.43750,341769.06250,2036.659912,GEN_Loki,1.5,NaN,0.0,WeapMini14_C,TorsoShot,Damage_Gun,350075.43750,385344.34375,3891.510010,T1_Rex,NaN,407
27,2020-10-10T12:14:41.989Z,LogPlayerTakeDamage,333806.43750,341769.06250,2036.659912,GEN_Loki,1.5,NaN,0.0,WeapMini14_C,LegShot,Damage_Gun,350168.31250,385429.50000,3886.389893,T1_Rex,NaN,413
65,2020-10-10T12:19:34.882Z,LogPlayerTakeDamage,463814.46875,424515.65625,3678.429932,ENT_kAyle,3.0,NaN,0.0,WeapHK416_C,LegShot,Damage_Gun,464184.00000,424342.50000,3650.199951,OPGG_Ayoh,NaN,1273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933,2020-10-10T12:32:38.409Z,LogPlayerTakeDamage,487604.56250,416040.75000,5390.790039,AF_Hansia,7.5,NaN,0.0,WeapBerylM762_C,PelvisShot,Damage_Gun,487641.31250,415188.00000,5491.270020,DNW_JeffLocka,NaN,5719
942,2020-10-10T12:32:41.376Z,LogPlayerTakeDamage,487392.62500,416051.87500,5439.899902,AF_Hansia,7.5,NaN,0.0,WeapBerylM762_C,TorsoShot,Damage_Gun,486308.62500,408862.03125,6115.009766,DNW_seoul,NaN,5752
945,2020-10-10T12:32:41.978Z,LogPlayerTakeDamage,487359.84375,416028.56250,5466.290039,AF_Hansia,7.5,NaN,0.0,WeapBerylM762_C,LegShot,Damage_Gun,486278.34375,408892.56250,6106.939941,DNW_seoul,NaN,5763
980,2020-10-10T12:33:01.722Z,LogPlayerTakeDamage,483989.75000,417588.78125,5368.750000,ENT_Seongjang,7.5,NaN,0.0,WeapBerylM762_C,HeadShot,Damage_Gun,486142.34375,417788.65625,4840.350098,AF_Hansia,NaN,5845
981,2020-10-10T12:33:01.798Z,LogPlayerTakeDamage,483990.03125,417585.62500,5370.589844,ENT_Seongjang,7.5,NaN,0.0,WeapBerylM762_C,TorsoShot,Damage_Gun,486142.06250,417791.50000,4839.129883,AF_Hansia,NaN,5847

In [26]:
dq = deque()
for tm in tml:
    if tm._T == 'LogItemEquip' and tm.common.is_game >= 1.0:
        try:
            dq.append([
                tm._D, 
                tm._T, 
                tm.character.location.x, 
                tm.character.location.y, 
                tm.character.location.z,
                tm.character.name, 
                tm.common.is_game, 
                tm.item.category,
                tm.item.item_id,
            ])
        except:
            pass

In [27]:
df_lie = pd.DataFrame(dq, 
    columns=['_D', '_T', 'character_location_x', 'character_location_y', 'character_location_z', 'character_name',
             'is_game', 'category', 'item_id'])

In [28]:
c1 = df_lie['item_id'].str.contains('Armor')
c2 = df_lie['item_id'].str.contains('Head')

In [29]:
df_groggy.columns

Index(['_D', '_T', 'attacker_location_x', 'attacker_location_y',
       'attacker_location_z', 'attacker_name', 'is_game', 'item_id', 'damage',
       'damage_causer_name', 'damage_reason', 'damage_type_category',
       'victim_location_x', 'victim_location_y', 'victim_location_z',
       'victim_name', 'distance', 'index'],
      dtype='object')

In [30]:
df_gro_part = df_groggy[['_D', '_T', 'attacker_location_x', 'attacker_location_y',
       'attacker_location_z', 'attacker_name', 'is_game', 'damage',
       'damage_causer_name', 'damage_reason', 'damage_type_category',
       'victim_location_x', 'victim_location_y', 'victim_location_z',
       'victim_name','index']]

In [31]:
df_lie_sorted = df_lie[c1 | c2].sort_values('character_name')
df_lie_sorted.columns

Index(['_D', '_T', 'character_location_x', 'character_location_y',
       'character_location_z', 'character_name', 'is_game', 'category',
       'item_id'],
      dtype='object')

In [32]:
df_lie_sorted.columns = ['_D', '_T', 'victim_location_x', 'victim_location_y',
       'victim_location_z', 'victim_name', 'is_game', 'category',
       'item_id']

In [33]:
df_gro_part2 = pd.concat([df_gro_part,df_lie_sorted])

In [34]:
df_gro_part2.sort_values('_D')

,_D,_T,attacker_location_x,attacker_location_y,attacker_location_z,attacker_name,is_game,damage,damage_causer_name,damage_reason,damage_type_category,victim_location_x,victim_location_y,victim_location_z,victim_name,index,category,item_id
0,2020-10-10T12:07:50.300Z,LogItemEquip,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,246977.96875,278977.28125,1150.150024,GEN_Aqua5,NaN,Equipment,Item_Head_F_01_Lv2_C
1,2020-10-10T12:07:50.303Z,LogItemEquip,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,360638.87500,401750.62500,3825.329834,ENT_Seongjang,NaN,Equipment,Item_Armor_D_01_Lv2_C
2,2020-10-10T12:07:50.401Z,LogItemEquip,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,288856.56250,266782.06250,1341.339966,VSG_Hulk,NaN,Equipment,Item_Armor_E_01_Lv1_C
7,2020-10-10T12:07:51.223Z,LogItemEquip,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,288803.28125,266746.00000,1341.339966,VSG_Hulk,NaN,Equipment,Item_Armor_D_01_Lv2_C
10,2020-10-10T12:07:51.636Z,LogItemEquip,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,300875.00000,544674.31250,267.589996,LVG_ZeniTh,NaN,Equipment,Item_Armor_D_01_Lv2_C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933,2020-10-10T12:32:38.409Z,LogPlayerTakeDamage,487604.56250,416040.75000,5390.790039,AF_Hansia,7.5,0.0,WeapBerylM762_C,PelvisShot,Damage_Gun,487641.31250,415188.00000,5491.270020,DNW_JeffLocka,5719.0,NaN,NaN
942,2020-10-10T12:32:41.376Z,LogPlayerTakeDamage,487392.62500,416051.87500,5439.899902,AF_Hansia,7.5,0.0,WeapBerylM762_C,TorsoShot,Damage_Gun,486308.62500,408862.03125,6115.009766,DNW_seoul,5752.0,NaN,NaN
945,2020-10-10T12:32:41.978Z,LogPlayerTakeDamage,487359.84375,416028.56250,5466.290039,AF_Hansia,7.5,0.0,WeapBerylM762_C,LegShot,Damage_Gun,486278.34375,408892.56250,6106.939941,DNW_seoul,5763.0,NaN,NaN
980,2020-10-10T12:33:01.722Z,LogPlayerTakeDamage,483989.75000,417588.78125,5368.750000,ENT_Seongjang,7.5,0.0,WeapBerylM762_C,HeadShot,Damage_Gun,486142.34375,417788.65625,4840.350098,AF_Hansia,5845.0,NaN,NaN
981,2020-10-10T12:33:01.798Z,LogPlayerTakeDamage,483990.03125,417585.62500,5370.589844,ENT_Seongjang,7.5,0.0,WeapBerylM762_C,TorsoShot,Damage_Gun,486142.06250,417791.50000,4839.129883,AF_Hansia,5847.0,NaN,NaN

In [35]:
df_lpd_sum = df_lpd.groupby('damage_causer_name')[['damage']].sum()

In [36]:
df_lpd_cnt = df_lpd.groupby('damage_causer_name')[['damage']].count()

In [37]:
df_lpd_part = df_lpd_sum.copy()

In [38]:
df_lpd_part['count'] = df_lpd_cnt

In [39]:
df_lpd_part

                                damage  count
damage_causer_name
BP_FireEffectController_C    92.000000     64
BP_MolotovFireDebuff_C      122.083063     34
Buggy_A_01_C                  2.759651      1
Buggy_A_02_C                 27.436416      3
Dacia_A_01_v2_C               2.008110      3
Dacia_A_02_v2_C              84.536567      2
Dacia_A_03_v2_Esports_C       0.445610      1
PlayerFemale_A_C             10.739585    381
PlayerMale_A_C               51.991495     39
ProjGrenade_C               833.692810     24
Uaz_B_01_esports_C           42.177386      4
WeapAK47_C                  267.275904     11
WeapBerylM762_C            3076.522957    172
WeapFNFal_C                3438.553749    146
WeapHK416_C                 664.084460     74
WeapM16A4_C                  67.734522      3
WeapMini14_C                547.949461     21
WeapSCAR-L_C                274.160368     10
WeapSKS_C                   278.668320     11

In [40]:
list(df_lpd['damage_causer_name'].unique())

['Dacia_A_02_v2_C',
 'PlayerMale_A_C',
 'PlayerFemale_A_C',
 'Uaz_B_01_esports_C',
 'Dacia_A_03_v2_Esports_C',
 'WeapMini14_C',
 'WeapFNFal_C',
 'Dacia_A_01_v2_C',
 'Buggy_A_01_C',
 'WeapSKS_C',
 'Buggy_A_02_C',
 'WeapHK416_C',
 'WeapM16A4_C',
 'WeapSCAR-L_C',
 'WeapBerylM762_C',
 'ProjGrenade_C',
 'BP_FireEffectController_C',
 'BP_MolotovFireDebuff_C',
 'WeapAK47_C']

In [41]:
dcm_list = ['WeapBerylM762_C',
 'WeapFNFal_C',
 'WeapSKS_C',
 'WeapMini14_C',
 'WeapHK416_C',
 'WeapAK47_C',
 'WeapSCAR-L_C']

In [42]:
for dcm in dcm_list:
    print(dcm)
    print(df_lpd[df_lpd['damage_causer_name'] == dcm]['damage'].describe())
    print()

WeapBerylM762_C
count    172.000000
mean      17.886761
std       15.970406
min        0.000000
25%        0.000000
50%       20.699999
75%       27.352750
max       64.860001
Name: damage, dtype: float64

WeapFNFal_C
count    146.000000
mean      23.551738
std       20.565478
min        0.000000
25%        0.000000
50%       27.404999
75%       36.540001
max       81.779991
Name: damage, dtype: float64

WeapSKS_C
count    11.000000
mean     25.333484
std       9.291836
min       5.791794
25%      23.689820
50%      25.145796
75%      32.979431
max      36.729000
Name: damage, dtype: float64

WeapMini14_C
count    21.000000
mean     26.092831
std      16.988697
min       0.000000
25%      19.017914
50%      26.174120
75%      28.810183
max      62.151035
Name: damage, dtype: float64

WeapHK416_C
count    74.000000
mean      8.974114
std      11.660541
min       0.000000
25%       0.000000
50%       0.000000
75%      21.088097
max      56.399998
Name: damage, dtype: float64

WeapAK47_C
count    11.000000
mean     24.297809
std      18.010026
min       0.000000
25%      17.960002
50%      26.789999
75%      28.199999
max      66.269997
Name: damage, dtype: float64

WeapSCAR-L_C
count    10.000000
mean     27.416037
std      15.322262
min       0.000000
25%      20.180655
50%      26.650001
75%      31.328282
max      57.809998
Name: damage, dtype: float64

In [43]:
df_lpd.describe()

,attacker_location_x,attacker_location_y,attacker_location_z,is_game,damage,victim_location_x,victim_location_y,victim_location_z
count,1004.000000,1004.000000,1004.000000,1004.000000,1004.000000,1004.000000,1004.000000,1004.000000
mean,489587.055186,409885.681960,5404.985882,5.001494,9.845439,489270.610869,410302.428629,5361.877281
std,45853.235373,24385.334425,3499.766263,1.347516,16.363218,45998.274695,24263.772013,3669.094485
min,222355.031250,245447.609375,131.559998,1.000000,0.000000,222355.031250,245447.609375,131.559998
25%,458679.875000,389128.453125,2458.159912,4.500000,0.000000,450315.640625,389496.617188,2344.869873
50%,491913.875000,414090.671875,5297.329834,4.500000,0.000000,491752.671875,413673.250000,5297.329834
75%,519559.890625,423032.046875,6790.399780,5.500000,20.745947,519272.093750,423693.210938,6729.762329
max,590858.125000,644963.062500,12303.819336,7.500000,100.000000,595780.187500,644963.062500,12304.459961

In [44]:
# 교전완성은 이번주.

# 그로기값보정도 이번주

# 오늘,목요일을 그렇게 진행하고

# 금요일은 최종프로젝트 준비.

# 교전에 대한 정의도 추가하는게 바람직함.

In [45]:
# c1 = df_lie['item_id'].str.contains('Armor')
# c2 = df_lie['item_id'].str.contains('Head')

In [46]:
df_battle

,_D,_T,attacker_location_x,attacker_location_y,attacker_location_z,attacker_name,is_game,item_id,damage,damage_causer_name,damage_reason,damage_type_category,victim_location_x,victim_location_y,victim_location_z,victim_name,distance,index
0,2020-10-10T12:08:20.195Z,LogPlayerTakeDamage,583198.18750,476487.093750,645.077515,QDR_Dlaks,1.0,NaN,3.904640,Dacia_A_02_v2_C,NonSpecific,Damage_VehicleCrashHit,583198.18750,476487.093750,645.077515,QDR_Dlaks,NaN,2
1,2020-10-10T12:08:33.241Z,LogPlayerTakeDamage,404082.90625,305939.281250,1306.339966,VLG_Spear,1.0,NaN,1.028725,PlayerMale_A_C,NonSpecific,Damage_Instant_Fall,404082.90625,305939.281250,1306.339966,VLG_Spear,NaN,3
2,2020-10-10T12:09:07.134Z,LogPlayerTakeDamage,357367.12500,318364.125000,518.260010,VLG_Lambu,1.0,NaN,1.347845,PlayerFemale_A_C,NonSpecific,Damage_Instant_Fall,357367.12500,318364.125000,518.260010,VLG_Lambu,NaN,9
3,2020-10-10T12:09:08.504Z,LogPlayerTakeDamage,356052.18750,245447.609375,4844.060059,EM_KiraV,1.0,NaN,15.549487,PlayerMale_A_C,NonSpecific,Damage_Instant_Fall,356052.18750,245447.609375,4844.060059,EM_KiraV,NaN,10
4,2020-10-10T12:10:35.350Z,LogPlayerTakeDamage,222355.03125,396152.781250,131.559998,T1_Starlord,1.0,NaN,0.670752,PlayerMale_A_C,NonSpecific,Damage_Instant_Fall,222355.03125,396152.781250,131.559998,T1_Starlord,NaN,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,2020-10-10T12:33:11.911Z,LogPlayerTakeDamage,484232.93750,417319.343750,5404.679688,ENT_Seongjang,7.5,NaN,0.000000,PlayerFemale_A_C,None,Damage_Groggy,484232.93750,417319.343750,5404.679688,ENT_Seongjang,NaN,5962
1003,2020-10-10T12:33:12.146Z,LogPlayerTakeDamage,485839.15625,417316.031250,5179.239746,AF_Hansia,7.5,NaN,0.000000,PlayerFemale_A_C,None,Damage_Groggy,485839.15625,417316.031250,5179.239746,AF_Hansia,NaN,5965
1002,2020-10-10T12:33:12.146Z,LogPlayerTakeDamage,485991.37500,416371.656250,5518.389648,ENT_Under,7.5,NaN,19.600006,WeapBerylM762_C,ArmShot,Damage_Gun,486197.06250,416638.562500,5387.290039,AF_daengchae,NaN,5966
57,2020-10-10T12:33:12.147Z,LogPlayerKill,483989.65625,417589.156250,5368.529785,ENT_Seongjang,7.5,NaN,NaN,PlayerFemale_A_C,None,Damage_Groggy,486143.00000,417782.062500,4843.189941,AF_Hansia,2224.878418,5967
58,2020-10-10T12:33:12.158Z,LogPlayerKill,485991.37500,416371.656250,5518.389648,ENT_Under,7.5,NaN,NaN,WeapBerylM762_C,ArmShot,Damage_Gun,486197.06250,416638.562500,5387.290039,AF_daengchae,361.570740,5968

In [47]:
df_dmg = df_gro_part2[['_D', '_T','damage', 'damage_causer_name','damage_reason','victim_name', 'category', 'item_id','index']]
df_dmg.sort_values('_D', inplace=True)
df_dmg

<ipython-input-47-b38150f6c5eb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dmg.sort_values('_D', inplace=True)

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,category,item_id,index
0,2020-10-10T12:07:50.300Z,LogItemEquip,NaN,NaN,NaN,GEN_Aqua5,Equipment,Item_Head_F_01_Lv2_C,NaN
1,2020-10-10T12:07:50.303Z,LogItemEquip,NaN,NaN,NaN,ENT_Seongjang,Equipment,Item_Armor_D_01_Lv2_C,NaN
2,2020-10-10T12:07:50.401Z,LogItemEquip,NaN,NaN,NaN,VSG_Hulk,Equipment,Item_Armor_E_01_Lv1_C,NaN
7,2020-10-10T12:07:51.223Z,LogItemEquip,NaN,NaN,NaN,VSG_Hulk,Equipment,Item_Armor_D_01_Lv2_C,NaN
10,2020-10-10T12:07:51.636Z,LogItemEquip,NaN,NaN,NaN,LVG_ZeniTh,Equipment,Item_Armor_D_01_Lv2_C,NaN
...,...,...,...,...,...,...,...,...,...
933,2020-10-10T12:32:38.409Z,LogPlayerTakeDamage,0.0,WeapBerylM762_C,PelvisShot,DNW_JeffLocka,NaN,NaN,5719.0
942,2020-10-10T12:32:41.376Z,LogPlayerTakeDamage,0.0,WeapBerylM762_C,TorsoShot,DNW_seoul,NaN,NaN,5752.0
945,2020-10-10T12:32:41.978Z,LogPlayerTakeDamage,0.0,WeapBerylM762_C,LegShot,DNW_seoul,NaN,NaN,5763.0
980,2020-10-10T12:33:01.722Z,LogPlayerTakeDamage,0.0,WeapBerylM762_C,HeadShot,AF_Hansia,NaN,NaN,5845.0
981,2020-10-10T12:33:01.798Z,LogPlayerTakeDamage,0.0,WeapBerylM762_C,TorsoShot,AF_Hansia,NaN,NaN,5847.0

In [48]:
c1 = df_dmg['item_id'].str.contains('Armor')
c2 = df_dmg['item_id'].str.contains('Head')

In [49]:
df_dmg['index']= range(0,len(df_dmg))

<ipython-input-49-6259500ba5c1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dmg['index']= range(0,len(df_dmg))

In [50]:
df_temp = pd.DataFrame(columns=list(df_dmg.columns))
for victim in list(df_dmg['victim_name'].unique()):
    c3 = df_dmg['victim_name']==victim
    try:
        df_dmg[c1 &c3].tail(1)['index']
    except:
        pass
    else:
        df_temp = df_temp.append(df_dmg[c1 &c3].tail(1))
        
    try:
        df_dmg[c2 &c3].tail(1)['index']
    except:
        pass
    else:
        df_temp = df_temp.append(df_dmg[c2 &c3].tail(1))

In [51]:
df_temp2 = df_temp.sort_values('_D')
df_temp3 = df_temp2[['victim_name', 'item_id']].sort_values('victim_name')
df_temp3['item_lvl'] = df_temp3['item_id'].str[-3]
df_temp3['item_type'] = df_temp3['item_id'].str.split('_').str[1]
df_temp4 = df_temp3[['victim_name', 'item_lvl', 'item_type']]
df_temp4

      victim_name item_lvl item_type
1042        AF_EJ        3     Armor
590         AF_EJ        2      Head
1106    AF_Hansia        3     Armor
674     AF_Hansia        2      Head
582      AF_R0wha        2      Head
...           ...      ...       ...
541   emT_Hwarang        2      Head
201      emT_Piky        2      Head
626      emT_Piky        3     Armor
419   emT_YunJong        2     Armor
102   emT_YunJong        2      Head

[121 rows x 3 columns]

### Groggy  상태의 Damage 보정작업.

In [52]:
df_partial = df_battle[df_battle['damage_type_category'] == 'Damage_Gun'][['_D', '_T', 'damage','damage_causer_name','damage_reason','victim_name','index']]
df_partial

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index
10,2020-10-10T12:14:10.105Z,LogPlayerTakeDamage,25.139475,WeapMini14_C,ArmShot,AF_daengchae,337
11,2020-10-10T12:14:30.091Z,LogPlayerTakeDamage,40.194000,WeapFNFal_C,TorsoShot,T1_Rex,373
12,2020-10-10T12:14:30.386Z,LogPlayerTakeDamage,59.806000,WeapFNFal_C,HeadShot,T1_Rex,375
19,2020-10-10T12:14:37.173Z,LogPlayerTakeDamage,0.000000,WeapFNFal_C,TorsoShot,T1_Rex,395
23,2020-10-10T12:14:39.547Z,LogPlayerTakeDamage,0.000000,WeapMini14_C,LegShot,T1_Rex,403
...,...,...,...,...,...,...,...
985,2020-10-10T12:33:04.563Z,LogPlayerTakeDamage,24.840000,WeapBerylM762_C,ArmShot,ENT_Seongjang,5884
987,2020-10-10T12:33:04.901Z,LogPlayerTakeDamage,14.095005,WeapBerylM762_C,HeadShot,ENT_Seongjang,5898
995,2020-10-10T12:33:09.547Z,LogPlayerTakeDamage,20.699999,WeapBerylM762_C,ArmShot,AF_daengchae,5926
1002,2020-10-10T12:33:12.146Z,LogPlayerTakeDamage,19.600006,WeapBerylM762_C,ArmShot,AF_daengchae,5966
58,2020-10-10T12:33:12.158Z,LogPlayerKill,NaN,WeapBerylM762_C,ArmShot,AF_daengchae,5968

In [53]:
df_partial.columns

Index(['_D', '_T', 'damage', 'damage_causer_name', 'damage_reason',
       'victim_name', 'index'],
      dtype='object')

In [54]:
df_partial = pd.merge(df_partial, df_temp4[df_temp4['item_type'] == 'Head'][['victim_name','item_lvl']], how='outer', on='victim_name')
df_partial.columns = ['_D', '_T', 'damage', 'damage_causer_name', 'damage_reason',
       'victim_name', 'index', 'head']
df_partial

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index,head
0,2020-10-10T12:14:10.105Z,LogPlayerTakeDamage,25.139475,WeapMini14_C,ArmShot,AF_daengchae,337.0,2
1,2020-10-10T12:25:45.253Z,LogPlayerTakeDamage,20.883791,WeapMini14_C,TorsoShot,AF_daengchae,4063.0,2
2,2020-10-10T12:26:01.703Z,LogPlayerTakeDamage,24.139650,WeapSKS_C,ArmShot,AF_daengchae,4183.0,2
3,2020-10-10T12:26:18.743Z,LogPlayerTakeDamage,26.401848,WeapSKS_C,TorsoShot,AF_daengchae,4479.0,2
4,2020-10-10T12:31:40.605Z,LogPlayerTakeDamage,59.385548,WeapFNFal_C,HeadShot,AF_daengchae,5496.0,2
...,...,...,...,...,...,...,...,...
484,2020-10-10T12:32:47.837Z,LogPlayerTakeDamage,27.600000,WeapBerylM762_C,TorsoShot,DNW_Draft,5790.0,2
485,2020-10-10T12:32:47.910Z,LogPlayerTakeDamage,14.440001,WeapBerylM762_C,TorsoShot,DNW_Draft,5792.0,2
486,2020-10-10T12:32:47.932Z,LogPlayerKill,NaN,WeapBerylM762_C,TorsoShot,DNW_Draft,5798.0,2
487,NaN,NaN,NaN,NaN,NaN,OPGG_Dumbo,NaN,2
488,NaN,NaN,NaN,NaN,NaN,QDR_yacha,NaN,2

In [55]:
df_partial = pd.merge(df_partial, df_temp4[df_temp4['item_type'] == 'Armor'][['victim_name','item_lvl']], how='outer', on='victim_name')
df_partial.columns = ['_D', '_T', 'damage', 'damage_causer_name', 'damage_reason',
       'victim_name','index', 'head', 'armor']
df_partial

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index,head,armor
0,2020-10-10T12:14:10.105Z,LogPlayerTakeDamage,25.139475,WeapMini14_C,ArmShot,AF_daengchae,337.0,2,3
1,2020-10-10T12:25:45.253Z,LogPlayerTakeDamage,20.883791,WeapMini14_C,TorsoShot,AF_daengchae,4063.0,2,3
2,2020-10-10T12:26:01.703Z,LogPlayerTakeDamage,24.139650,WeapSKS_C,ArmShot,AF_daengchae,4183.0,2,3
3,2020-10-10T12:26:18.743Z,LogPlayerTakeDamage,26.401848,WeapSKS_C,TorsoShot,AF_daengchae,4479.0,2,3
4,2020-10-10T12:31:40.605Z,LogPlayerTakeDamage,59.385548,WeapFNFal_C,HeadShot,AF_daengchae,5496.0,2,3
...,...,...,...,...,...,...,...,...,...
485,2020-10-10T12:32:47.910Z,LogPlayerTakeDamage,14.440001,WeapBerylM762_C,TorsoShot,DNW_Draft,5792.0,2,2
486,2020-10-10T12:32:47.932Z,LogPlayerKill,NaN,WeapBerylM762_C,TorsoShot,DNW_Draft,5798.0,2,2
487,NaN,NaN,NaN,NaN,NaN,OPGG_Dumbo,NaN,2,3
488,NaN,NaN,NaN,NaN,NaN,QDR_yacha,NaN,2,2
489,NaN,NaN,NaN,NaN,NaN,ENT_indigo,NaN,NaN,3

In [56]:
df_partial.dropna(inplace=True)

In [58]:
df_weight = pd.DataFrame({'damage_reason':['ArmShot', 'HeadShot', 'LegShot', 'PelvisShot', 'TorsoShot'],
                    'damage_reason_weight':[140/3, 100, 140/3, 95, 310/3]
                    })

In [59]:
df_weight

  damage_reason  damage_reason_weight
0       ArmShot             46.666667
1      HeadShot            100.000000
2       LegShot             46.666667
3    PelvisShot             95.000000
4     TorsoShot            103.333333

In [67]:
df_weapon = pd.DataFrame({'damage_causer_name':['WeapSCAR-L_C', 'WeapAK47_C', 'WeapM16A4_C', 'WeapFNFal_C', 'WeapBerylM762_C', 'WeapHK416_C', 'WeapSKS_C', 'WeapMini14_C'],
                          'damage_causer_mean_dmg':[43.76,48.95,44.79,60.15,45.84,41.69,56.91,50.44,]})

In [68]:
df_weapon

  damage_causer_name  damage_causer_mean_dmg
0       WeapSCAR-L_C                   43.76
1         WeapAK47_C                   48.95
2        WeapM16A4_C                   44.79
3        WeapFNFal_C                   60.15
4    WeapBerylM762_C                   45.84
5        WeapHK416_C                   41.69
6          WeapSKS_C                   56.91
7       WeapMini14_C                   50.44

In [62]:
df_partial

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index,head,armor
0,2020-10-10T12:14:10.105Z,LogPlayerTakeDamage,25.139475,WeapMini14_C,ArmShot,AF_daengchae,337.0,2,3
1,2020-10-10T12:25:45.253Z,LogPlayerTakeDamage,20.883791,WeapMini14_C,TorsoShot,AF_daengchae,4063.0,2,3
2,2020-10-10T12:26:01.703Z,LogPlayerTakeDamage,24.139650,WeapSKS_C,ArmShot,AF_daengchae,4183.0,2,3
3,2020-10-10T12:26:18.743Z,LogPlayerTakeDamage,26.401848,WeapSKS_C,TorsoShot,AF_daengchae,4479.0,2,3
4,2020-10-10T12:31:40.605Z,LogPlayerTakeDamage,59.385548,WeapFNFal_C,HeadShot,AF_daengchae,5496.0,2,3
...,...,...,...,...,...,...,...,...,...
481,2020-10-10T12:31:30.068Z,LogPlayerTakeDamage,29.341217,WeapFNFal_C,TorsoShot,ENT_Under,5476.0,3,3
482,2020-10-10T12:32:47.659Z,LogPlayerTakeDamage,30.360001,WeapBerylM762_C,TorsoShot,DNW_Draft,5785.0,2,2
483,2020-10-10T12:32:47.747Z,LogPlayerTakeDamage,27.600000,WeapBerylM762_C,TorsoShot,DNW_Draft,5788.0,2,2
484,2020-10-10T12:32:47.837Z,LogPlayerTakeDamage,27.600000,WeapBerylM762_C,TorsoShot,DNW_Draft,5790.0,2,2
485,2020-10-10T12:32:47.910Z,LogPlayerTakeDamage,14.440001,WeapBerylM762_C,TorsoShot,DNW_Draft,5792.0,2,2

In [66]:
df_partial_2 = pd.merge(df_partial,df_weight)
df_partial_2

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index,head,armor,damage_reason_weight
0,2020-10-10T12:14:10.105Z,LogPlayerTakeDamage,25.139475,WeapMini14_C,ArmShot,AF_daengchae,337.0,2,3,46.666667
1,2020-10-10T12:26:01.703Z,LogPlayerTakeDamage,24.139650,WeapSKS_C,ArmShot,AF_daengchae,4183.0,2,3,46.666667
2,2020-10-10T12:33:09.547Z,LogPlayerTakeDamage,20.699999,WeapBerylM762_C,ArmShot,AF_daengchae,5926.0,2,3,46.666667
3,2020-10-10T12:33:12.146Z,LogPlayerTakeDamage,19.600006,WeapBerylM762_C,ArmShot,AF_daengchae,5966.0,2,3,46.666667
4,2020-10-10T12:21:48.880Z,LogPlayerTakeDamage,0.000000,WeapHK416_C,ArmShot,LVG_Sparrow,2029.0,2,2,46.666667
...,...,...,...,...,...,...,...,...,...,...
393,2020-10-10T12:25:28.893Z,LogPlayerTakeDamage,27.428398,WeapBerylM762_C,PelvisShot,GRF_2heart,3940.0,2,2,95.000000
394,2020-10-10T12:26:24.634Z,LogPlayerTakeDamage,27.600000,WeapBerylM762_C,PelvisShot,GRF_2heart,4573.0,2,2,95.000000
395,2020-10-10T12:25:44.186Z,LogPlayerTakeDamage,0.000000,WeapHK416_C,PelvisShot,KP_Black9,4033.0,2,2,95.000000
396,2020-10-10T12:26:14.631Z,LogPlayerTakeDamage,12.369999,WeapFNFal_C,PelvisShot,emT_Piky,4418.0,2,3,95.000000
397,2020-10-10T12:26:56.166Z,LogPlayerTakeDamage,0.000000,WeapBerylM762_C,PelvisShot,AZG_Rozar,4813.0,2,3,95.000000

In [70]:
df_partial_3 = pd.merge(df_partial_2,df_weapon)
df_partial_3

,_D,_T,damage,damage_causer_name,damage_reason,victim_name,index,head,armor,damage_reason_weight,damage_causer_mean_dmg
0,2020-10-10T12:14:10.105Z,LogPlayerTakeDamage,25.139475,WeapMini14_C,ArmShot,AF_daengchae,337.0,2,3,46.666667,50.44
1,2020-10-10T12:20:32.992Z,LogPlayerTakeDamage,23.357552,WeapMini14_C,ArmShot,VSG_DG98,1713.0,2,3,46.666667,50.44
2,2020-10-10T12:23:14.845Z,LogPlayerTakeDamage,12.355537,WeapMini14_C,ArmShot,GEN_Pio,2648.0,2,2,46.666667,50.44
3,2020-10-10T12:25:45.253Z,LogPlayerTakeDamage,20.883791,WeapMini14_C,TorsoShot,AF_daengchae,4063.0,2,3,103.333333,50.44
4,2020-10-10T12:14:40.486Z,LogPlayerTakeDamage,0.000000,WeapMini14_C,TorsoShot,T1_Rex,407.0,2,2,103.333333,50.44
...,...,...,...,...,...,...,...,...,...,...,...
393,2020-10-10T12:23:31.347Z,LogPlayerTakeDamage,26.905909,WeapAK47_C,TorsoShot,GEN_Loki,2878.0,2,2,103.333333,48.95
394,2020-10-10T12:23:46.636Z,LogPlayerTakeDamage,28.199999,WeapAK47_C,TorsoShot,GEN_Inonix,3136.0,2,2,103.333333,48.95
395,2020-10-10T12:23:52.601Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,GEN_Aqua5,3213.0,2,2,103.333333,48.95
396,2020-10-10T12:23:52.711Z,LogPlayerTakeDamage,26.789999,WeapAK47_C,TorsoShot,GEN_Aqua5,3218.0,2,2,103.333333,48.95
397,2020-10-10T12:28:20.070Z,LogPlayerTakeDamage,66.269997,WeapAK47_C,HeadShot,SP_NEFiEX,5174.0,2,2,100.000000,48.95

## train, test 분리

In [83]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler

In [88]:
df_partial_4 = df_partial_3[['damage', 'head', 'armor', 'damage_reason_weight','damage_causer_mean_dmg' ]]
df_partial_4

        damage head armor  damage_reason_weight  damage_causer_mean_dmg
0    25.139475    2     3             46.666667                   50.44
1    23.357552    2     3             46.666667                   50.44
2    12.355537    2     2             46.666667                   50.44
3    20.883791    2     3            103.333333                   50.44
4     0.000000    2     2            103.333333                   50.44
..         ...  ...   ...                   ...                     ...
393  26.905909    2     2            103.333333                   48.95
394  28.199999    2     2            103.333333                   48.95
395  26.789999    2     2            103.333333                   48.95
396  26.789999    2     2            103.333333                   48.95
397  66.269997    2     2            100.000000                   48.95

[398 rows x 5 columns]

In [97]:
df_partial_groggy = df_partial_4[df_partial_4['damage'] == 0]
df_partial_groggy

     damage head armor  damage_reason_weight  damage_causer_mean_dmg
4       0.0    2     2            103.333333                   50.44
16      0.0    2     2             46.666667                   50.44
17      0.0    2     2             46.666667                   50.44
38      0.0    2     2             46.666667                   45.84
42      0.0    2     2             46.666667                   45.84
..      ...  ...   ...                   ...                     ...
369     0.0    2     2             95.000000                   60.15
370     0.0    2     2             95.000000                   60.15
380     0.0    2     2            103.333333                   43.76
388     0.0    2     2            103.333333                   48.95
389     0.0    2     2            103.333333                   48.95

[125 rows x 5 columns]

In [99]:
df_partial_5 = df_partial_4[df_partial_4['damage'] != 0]
df_partial_5

        damage head armor  damage_reason_weight  damage_causer_mean_dmg
0    25.139475    2     3             46.666667                   50.44
1    23.357552    2     3             46.666667                   50.44
2    12.355537    2     2             46.666667                   50.44
3    20.883791    2     3            103.333333                   50.44
5    31.877998    2     2            103.333333                   50.44
..         ...  ...   ...                   ...                     ...
393  26.905909    2     2            103.333333                   48.95
394  28.199999    2     2            103.333333                   48.95
395  26.789999    2     2            103.333333                   48.95
396  26.789999    2     2            103.333333                   48.95
397  66.269997    2     2            100.000000                   48.95

[273 rows x 5 columns]

In [102]:
robustScaler = RobustScaler()
robustScaler.fit(df_partial_5)
df_partial_scaled = robustScaler.transform(df_partial_5)
df_partial_scaled

array([[-0.13579262,  0.        ,  1.        , -1.        ,  0.32145353],
       [-0.32747293,  0.        ,  1.        , -1.        ,  0.32145353],
       [-1.5109523 ,  0.        ,  0.        , -1.        ,  0.32145353],
       ...,
       [ 0.04175316,  0.        ,  0.        ,  0.        ,  0.21733054],
       [ 0.04175316,  0.        ,  0.        ,  0.        ,  0.21733054],
       [ 4.28859033,  0.        ,  0.        , -0.05882353,  0.21733054]])

In [107]:
df_eval = pd.DataFrame(data =df_partial_scaled, columns=['damage','head','armor','damage_reason_weight','damage_causer_mean_dmg'] )
df_eval

       damage  head  armor  damage_reason_weight  damage_causer_mean_dmg
0   -0.135793   0.0    1.0             -1.000000                0.321454
1   -0.327473   0.0    1.0             -1.000000                0.321454
2   -1.510952   0.0    0.0             -1.000000                0.321454
3   -0.593574   0.0    1.0              0.000000                0.321454
4    0.589066   0.0    0.0              0.000000                0.321454
..        ...   ...    ...                   ...                     ...
268  0.054221   0.0    0.0              0.000000                0.217331
269  0.193426   0.0    0.0              0.000000                0.217331
270  0.041753   0.0    0.0              0.000000                0.217331
271  0.041753   0.0    0.0              0.000000                0.217331
272  4.288590   0.0    0.0             -0.058824                0.217331

[273 rows x 5 columns]

In [111]:
df_x = df_eval.drop('damage', axis=1)
df_y = df_eval['damage']

In [112]:
X_train, X_test, y_train, y_test = train_test_split( df_x, df_y, test_size=0.2, random_state=42)